version: "3.8"
services:
  app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    env_file:
      - .dev.env
    ports:
      - "8000:8000"
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: family_budget
    volumes:
      - family-budget-data:/var/lib/postgresql/data
volumes:
  family-budget-data: